/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ibfb.lists.report;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import org.openide.util.NbBundle;

public final class LabelReportVisualPanel1 extends JPanel {

    private Integer[] selectedFields = new Integer[9];
    
    /**
     * Creates new form LabelReportVisualPanel1
     */
    public LabelReportVisualPanel1() {
        initComponents();
    }

    public void assignFields(List<String> fields) {
        populateCombos(fields);
    }

    private void populateCombos(List<String> fields) {
        populateCombo(fields, cboLabel0);        
        populateCombo(fields, cboLabel1);
        populateCombo(fields, cboLabel2);
        populateCombo(fields, cboLabel3);
        populateCombo(fields, cboLabel4);
        populateCombo(fields, cboLabel5);
        populateCombo(fields, cboLabel6);
        populateCombo(fields, cboLabel7);
        populateCombo(fields, cboLabel8);
    }

    private void populateCombo(List<String> fields, JComboBox combo) {
        DefaultComboBoxModel dcbm = (DefaultComboBoxModel) combo.getModel();
        dcbm.removeAllElements();
        dcbm.addElement(NbBundle.getMessage(LabelReportVisualPanel1.class, "LabelReportVisualPanel1.selectField"));
        for (String field : fields) {
            dcbm.addElement(field);
        }
    }

    @Override
    public String getName() {
        return NbBundle.getMessage(LabelReportVisualPanel1.class, "PrintLabels");
    }

    private void updatePreviewLabel(JLabel previewLabel, JComboBox fieldCombo) {
        if (fieldCombo.getSelectedIndex() != -1) {
            if (fieldCombo.getSelectedIndex() == 0) {
                previewLabel.setText("");
            } else {
                previewLabel.setText(fieldCombo.getSelectedItem().toString());
            }
        }

    }
    
    public boolean smallReportSelected() {
        return rBtnSmall.isSelected();
    }

    public Integer[] getSelectedFields() {
        selectedFields[ReportBean.BARCODE]= cboLabel0.getSelectedIndex();
        selectedFields[ReportBean.LABEL_1]= cboLabel1.getSelectedIndex();
        selectedFields[ReportBean.LABEL_2]= cboLabel2.getSelectedIndex();
        selectedFields[ReportBean.LABEL_3]= cboLabel3.getSelectedIndex();
        selectedFields[ReportBean.LABEL_4]= cboLabel4.getSelectedIndex();
        selectedFields[ReportBean.LABEL_5]= cboLabel5.getSelectedIndex();
        selectedFields[ReportBean.LABEL_6]= cboLabel6.getSelectedIndex();
        selectedFields[ReportBean.LABEL_7]= cboLabel7.getSelectedIndex();
        selectedFields[ReportBean.LABEL_8]= cboLabel8.getSelectedIndex();        
        
        return selectedFields;
        
    }

    public void setSelectedFields(Integer[] selectedFields) {
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpSize = new javax.swing.ButtonGroup();
        pnlDetail = new javax.swing.JPanel();
        lblLabel1 = new javax.swing.JLabel();
        lblLabel2 = new javax.swing.JLabel();
        cboLabel1 = new javax.swing.JComboBox();
        cboLabel2 = new javax.swing.JComboBox();
        lblLabel3 = new javax.swing.JLabel();
        lblLabel4 = new javax.swing.JLabel();
        cboLabel3 = new javax.swing.JComboBox();
        cboLabel4 = new javax.swing.JComboBox();
        lblLabel5 = new javax.swing.JLabel();
        cboLabel5 = new javax.swing.JComboBox();
        lblLabel6 = new javax.swing.JLabel();
        cboLabel6 = new javax.swing.JComboBox();
        lblLabel7 = new javax.swing.JLabel();
        lblLabel8 = new javax.swing.JLabel();
        cboLabel7 = new javax.swing.JComboBox();
        cboLabel8 = new javax.swing.JComboBox();
        lblBigLabels = new javax.swing.JRadioButton();
        rBtnSmall = new javax.swing.JRadioButton();
        lblSize = new javax.swing.JLabel();
        lblBarCode = new javax.swing.JLabel();
        cboLabel0 = new javax.swing.JComboBox();
        pnlPreview = new javax.swing.JPanel();
        lblPreview1 = new javax.swing.JLabel();
        lblPreview2 = new javax.swing.JLabel();
        lblPreview3 = new javax.swing.JLabel();
        lblPreview4 = new javax.swing.JLabel();
        lblPreview5 = new javax.swing.JLabel();
        lblPreview6 = new javax.swing.JLabel();
        lblPreview7 = new javax.swing.JLabel();
        lblPreview8 = new javax.swing.JLabel();
        lblBarcode = new javax.swing.JLabel();

        pnlDetail.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(LabelReportVisualPanel1.class, "LabelReportVisualPanel1.pnlDetail.border.title"))); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblLabel1, org.openide.util.NbBundle.getMessage(LabelReportVisualPanel1.class, "LabelReportVisualPanel1.lblLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblLabel2, org.openide.util.NbBundle.getMessage(LabelReportVisualPanel1.class, "LabelReportVisualPanel1.lblLabel2.text")); // NOI18N

        cboLabel1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboLabel1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboLabel1ItemStateChanged(evt);
            }
        });

        cboLabel2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboLabel2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboLabel2ItemStateChanged(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(lblLabel3, org.openide.util.NbBundle.getMessage(LabelReportVisualPanel1.class, "LabelReportVisualPanel1.lblLabel3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblLabel4, org.openide.util.NbBundle.getMessage(LabelReportVisualPanel1.class, "LabelReportVisualPanel1.lblLabel4.text")); // NOI18N

        cboLabel3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboLabel3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboLabel3ItemStateChanged(evt);
            }
        });

        cboLabel4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboLabel4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboLabel4ItemStateChanged(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(lblLabel5, org.openide.util.NbBundle.getMessage(LabelReportVisualPanel1.class, "LabelReportVisualPanel1.lblLabel5.text")); // NOI18N

        cboLabel5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboLabel5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboLabel5ItemStateChanged(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(lblLabel6, org.openide.util.NbBundle.getMessage(LabelReportVisualPanel1.class, "LabelReportVisualPanel1.lblLabel6.text")); // NOI18N

        cboLabel6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboLabel6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboLabel6ItemStateChanged(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(lblLabel7, org.openide.util.NbBundle.getMessage(LabelReportVisualPanel1.class, "LabelReportVisualPanel1.lblLabel7.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblLabel8, org.openide.util.NbBundle.getMessage(LabelReportVisualPanel1.class, "LabelReportVisualPanel1.lblLabel8.text")); // NOI18N

        cboLabel7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboLabel7.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboLabel7ItemStateChanged(evt);
            }
        });

        cboLabel8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboLabel8.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboLabel8ItemStateChanged(evt);
            }
        });

        btnGrpSize.add(lblBigLabels);
        lblBigLabels.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(lblBigLabels, org.openide.util.NbBundle.getMessage(LabelReportVisualPanel1.class, "LabelReportVisualPanel1.lblBigLabels.text")); // NOI18N

        btnGrpSize.add(rBtnSmall);
        org.openide.awt.Mnemonics.setLocalizedText(rBtnSmall, org.openide.util.NbBundle.getMessage(LabelReportVisualPanel1.class, "LabelReportVisualPanel1.rBtnSmall.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblSize, org.openide.util.NbBundle.getMessage(LabelReportVisualPanel1.class, "LabelReportVisualPanel1.lblSize.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblBarCode, org.openide.util.NbBundle.getMessage(LabelReportVisualPanel1.class, "LabelReportVisualPanel1.lblBarCode.text")); // NOI18N

        cboLabel0.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pnlDetailLayout = new javax.swing.GroupLayout(pnlDetail);
        pnlDetail.setLayout(pnlDetailLayout);
        pnlDetailLayout.setHorizontalGroup(
            pnlDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetailLayout.createSequentialGroup()
                .addGroup(pnlDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDetailLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(pnlDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rBtnSmall)
                            .addComponent(lblBigLabels)))
                    .addGroup(pnlDetailLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cboLabel0, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pnlDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLabel1)
                                    .addComponent(lblLabel3)
                                    .addComponent(cboLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLabel5)
                                    .addComponent(cboLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLabel7)
                                    .addComponent(cboLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBarCode))
                                .addGroup(pnlDetailLayout.createSequentialGroup()
                                    .addComponent(lblSize)
                                    .addGap(89, 89, 89))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLabel4)
                            .addComponent(lblLabel2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblLabel8)
                                .addGroup(pnlDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblLabel6)
                                        .addComponent(cboLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cboLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(cboLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12))
        );

        pnlDetailLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cboLabel1, cboLabel3, cboLabel5, cboLabel7});

        pnlDetailLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cboLabel2, cboLabel4, cboLabel6, cboLabel8});

        pnlDetailLayout.setVerticalGroup(
            pnlDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetailLayout.createSequentialGroup()
                .addComponent(lblBarCode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cboLabel0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLabel1)
                    .addComponent(lblLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLabel3)
                    .addComponent(lblLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLabel5)
                    .addComponent(lblLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLabel7)
                    .addComponent(lblLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(lblSize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBigLabels)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rBtnSmall)
                .addContainerGap())
        );

        pnlPreview.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(LabelReportVisualPanel1.class, "LabelReportVisualPanel1.pnlPreview.border.title"))); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblPreview1, org.openide.util.NbBundle.getMessage(LabelReportVisualPanel1.class, "LabelReportVisualPanel1.lblPreview3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblPreview2, org.openide.util.NbBundle.getMessage(LabelReportVisualPanel1.class, "LabelReportVisualPanel1.lblPreview3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblPreview3, org.openide.util.NbBundle.getMessage(LabelReportVisualPanel1.class, "LabelReportVisualPanel1.lblPreview3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblPreview4, org.openide.util.NbBundle.getMessage(LabelReportVisualPanel1.class, "LabelReportVisualPanel1.lblPreview3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblPreview5, org.openide.util.NbBundle.getMessage(LabelReportVisualPanel1.class, "LabelReportVisualPanel1.lblPreview3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblPreview6, org.openide.util.NbBundle.getMessage(LabelReportVisualPanel1.class, "LabelReportVisualPanel1.lblPreview3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblPreview7, org.openide.util.NbBundle.getMessage(LabelReportVisualPanel1.class, "LabelReportVisualPanel1.lblPreview3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblPreview8, org.openide.util.NbBundle.getMessage(LabelReportVisualPanel1.class, "LabelReportVisualPanel1.lblPreview3.text")); // NOI18N

        lblBarcode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ibfb/lists/images/barcodepreview.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(lblBarcode, org.openide.util.NbBundle.getMessage(LabelReportVisualPanel1.class, "LabelReportVisualPanel1.lblBarcode.text")); // NOI18N

        javax.swing.GroupLayout pnlPreviewLayout = new javax.swing.GroupLayout(pnlPreview);
        pnlPreview.setLayout(pnlPreviewLayout);
        pnlPreviewLayout.setHorizontalGroup(
            pnlPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPreviewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblBarcode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlPreviewLayout.createSequentialGroup()
                        .addGroup(pnlPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPreview7)
                            .addComponent(lblPreview5)
                            .addComponent(lblPreview3)
                            .addComponent(lblPreview1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPreview2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPreview4)
                            .addComponent(lblPreview6)
                            .addComponent(lblPreview8))))
                .addGap(86, 86, 86))
        );

        pnlPreviewLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblPreview1, lblPreview3, lblPreview5, lblPreview7});

        pnlPreviewLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblPreview2, lblPreview4, lblPreview6, lblPreview8});

        pnlPreviewLayout.setVerticalGroup(
            pnlPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPreviewLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(lblBarcode)
                .addGap(30, 30, 30)
                .addGroup(pnlPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPreview1)
                    .addComponent(lblPreview2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPreview3)
                    .addComponent(lblPreview4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPreview5)
                    .addComponent(lblPreview6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPreview7)
                    .addComponent(lblPreview8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPreview, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPreview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cboLabel1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboLabel1ItemStateChanged
        updatePreviewLabel(lblPreview1, cboLabel1);
    }//GEN-LAST:event_cboLabel1ItemStateChanged

    private void cboLabel2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboLabel2ItemStateChanged
        updatePreviewLabel(lblPreview2, cboLabel2);
    }//GEN-LAST:event_cboLabel2ItemStateChanged

    private void cboLabel3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboLabel3ItemStateChanged
        updatePreviewLabel(lblPreview3, cboLabel3);
    }//GEN-LAST:event_cboLabel3ItemStateChanged

    private void cboLabel4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboLabel4ItemStateChanged
        updatePreviewLabel(lblPreview4, cboLabel4);
    }//GEN-LAST:event_cboLabel4ItemStateChanged

    private void cboLabel5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboLabel5ItemStateChanged
        updatePreviewLabel(lblPreview5, cboLabel5);
    }//GEN-LAST:event_cboLabel5ItemStateChanged

    private void cboLabel6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboLabel6ItemStateChanged
        updatePreviewLabel(lblPreview6, cboLabel6);
    }//GEN-LAST:event_cboLabel6ItemStateChanged

    private void cboLabel7ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboLabel7ItemStateChanged
        updatePreviewLabel(lblPreview7, cboLabel7);
    }//GEN-LAST:event_cboLabel7ItemStateChanged

    private void cboLabel8ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboLabel8ItemStateChanged
        updatePreviewLabel(lblPreview8, cboLabel8);
    }//GEN-LAST:event_cboLabel8ItemStateChanged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrpSize;
    private javax.swing.JComboBox cboLabel0;
    private javax.swing.JComboBox cboLabel1;
    private javax.swing.JComboBox cboLabel2;
    private javax.swing.JComboBox cboLabel3;
    private javax.swing.JComboBox cboLabel4;
    private javax.swing.JComboBox cboLabel5;
    private javax.swing.JComboBox cboLabel6;
    private javax.swing.JComboBox cboLabel7;
    private javax.swing.JComboBox cboLabel8;
    private javax.swing.JLabel lblBarCode;
    private javax.swing.JLabel lblBarcode;
    private javax.swing.JRadioButton lblBigLabels;
    private javax.swing.JLabel lblLabel1;
    private javax.swing.JLabel lblLabel2;
    private javax.swing.JLabel lblLabel3;
    private javax.swing.JLabel lblLabel4;
    private javax.swing.JLabel lblLabel5;
    private javax.swing.JLabel lblLabel6;
    private javax.swing.JLabel lblLabel7;
    private javax.swing.JLabel lblLabel8;
    private javax.swing.JLabel lblPreview1;
    private javax.swing.JLabel lblPreview2;
    private javax.swing.JLabel lblPreview3;
    private javax.swing.JLabel lblPreview4;
    private javax.swing.JLabel lblPreview5;
    private javax.swing.JLabel lblPreview6;
    private javax.swing.JLabel lblPreview7;
    private javax.swing.JLabel lblPreview8;
    private javax.swing.JLabel lblSize;
    private javax.swing.JPanel pnlDetail;
    private javax.swing.JPanel pnlPreview;
    private javax.swing.JRadioButton rBtnSmall;
    // End of variables declaration//GEN-END:variables
}
