/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ibfb.studyeditor.layout;

import ibfb.domain.core.DesignBean;
import ibfb.studyeditor.layout.model.FieldLayoutTableModel;
import ibfb.studyeditor.layout.model.FieldPlanBean;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;

public final class FieldmapVisualPanel1 extends JPanel {

    private List<DesignBean> designList;
    private List<FieldPlanBean> fieldPlanList;

    /**
     * Creates new form FieldmapVisualPanel1
     */
    public FieldmapVisualPanel1(List<DesignBean> designList) {
        initComponents();
        this.designList = designList;
        createTable();
    }
    
    private void createTable() {
        fieldPlanList = new ArrayList<FieldPlanBean>();
        
        for (DesignBean db : designList) {
            FieldPlanBean fpb = new FieldPlanBean();
            fpb.setTrial(db.getTrialNumber());
            fieldPlanList.add(fpb);
        }
        
        FieldLayoutTableModel fltm = new FieldLayoutTableModel(fieldPlanList);
        tblFieldplan.setModel(fltm);
    }

    @Override
    public String getName() {
        return "Step #1";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrlPlan = new javax.swing.JScrollPane();
        tblFieldplan = new javax.swing.JTable();

        tblFieldplan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrlPlan.setViewportView(tblFieldplan);
        tblFieldplan.getColumnModel().getColumn(0).setHeaderValue(org.openide.util.NbBundle.getMessage(FieldmapVisualPanel1.class, "FieldmapVisualPanel1.tblFieldplan.columnModel.title0")); // NOI18N
        tblFieldplan.getColumnModel().getColumn(1).setHeaderValue(org.openide.util.NbBundle.getMessage(FieldmapVisualPanel1.class, "FieldmapVisualPanel1.tblFieldplan.columnModel.title1")); // NOI18N
        tblFieldplan.getColumnModel().getColumn(2).setHeaderValue(org.openide.util.NbBundle.getMessage(FieldmapVisualPanel1.class, "FieldmapVisualPanel1.tblFieldplan.columnModel.title2")); // NOI18N
        tblFieldplan.getColumnModel().getColumn(3).setHeaderValue(org.openide.util.NbBundle.getMessage(FieldmapVisualPanel1.class, "FieldmapVisualPanel1.tblFieldplan.columnModel.title3")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrlPlan, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scrlPlan, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrlPlan;
    private javax.swing.JTable tblFieldplan;
    // End of variables declaration//GEN-END:variables
}
